### ISSUE TITLE
GO_GIT_DESCRIBE_SYMBOL=main.version seems to break the build.

### ISSUE THREAD

**Issue by jelder** [kr/heroku-buildpack-go#73]
Adding `GO_GIT_DESCRIBE_SYMBOL` as described at https://github.com/kr/heroku-buildpack-go#setting-the-version-at-build-time seems to cause the build to fail.

```
-----> Fetching custom git buildpack... done
-----> Go app detected
-----> Using go1.2
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

 !     Push rejected, failed to compile Go app
```

![screenshot 2015-01-14 11 39 05](https://cloud.githubusercontent.com/assets/38099/5742674/fc3156e0-9be1-11e4-81f7-cb1708e447cc.png)

Repo is https://github.com/jelder/beacon/

**Comment by kr** [comment]
Unfortunately, it is not possible for this feature to work correctly on heroku, both because the buildpack runs inside of a pre-commit hook, and because heroku is in the process of removing git artifacts from the build process entirely.

I'll have to remove the feature from this buildpack.

So sorry! I still want to find a way to get similar functionality, but currently it can't be done.

**Comment by kr** [comment]
Removed in 36476a80efb196676091c07acfe54e4443f974e3.
